SELECT ID, FISH_NAME, LENGTH
    FROM (
            SELECT I.FISH_TYPE, FISH_NAME, MAX(LENGTH) AS LEN
            FROM FISH_INFO I, FISH_NAME_INFO N
            WHERE I.FISH_TYPE = N.FISH_TYPE
            GROUP BY I.FISH_TYPE, FISH_NAME
        ) A
        , FISH_INFO F
    WHERE A.FISH_TYPE = F.FISH_TYPE
    AND A.LEN = F.LENGTH
    ORDER BY ID